# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' created on 2/14/2022: this one use stratified model
NULL

compute_facility_idx <- function(facility, num_facility) {
    .Call('_tdrecur_compute_facility_idx', PACKAGE = 'tdrecur', facility, num_facility)
}

#' this function calculates Sm (1 by p), sum of z in event set; O, the vector of total events in each 
#' facility; num_events, number of all events; events_per_day_facility, number of events each day in each facility
#'@param hosp_begin matrix of hospitalization begin date
#'@param max_d the largest number of hospitalization in each segment
#'@param D number of distinct failure time number of days)
#'@param z time-independent variables
compute_d12 <- function(hosp_begin, max_d, D, z, Z_tv, t_tv, max_v, facility, num_facility) {
    .Call('_tdrecur_compute_d12', PACKAGE = 'tdrecur', hosp_begin, max_d, D, z, Z_tv, t_tv, max_v, facility, num_facility)
}

#'@param l log partial likelihood
#'@param S0 D+1 vector, we will do day 0 (begining of day 1) to day D (end of day D)
#'@param t_start a vector of segment start date, starting from 1, minus 1 when using it.
#'@param t_end a vector of segment end date, starting from 1.
#'@param Sm 1 by p vector
#'@param ym number of changes on each day
ddloglik_cpp6 <- function(l, lchange, L1, L2, t_start, t_end, Sm, events_per_day_facility, z, Z_tv, t_tv, max_v, beta, N, facility_idx, hosp_begin, max_d) {
    invisible(.Call('_tdrecur_ddloglik_cpp6', PACKAGE = 'tdrecur', l, lchange, L1, L2, t_start, t_end, Sm, events_per_day_facility, z, Z_tv, t_tv, max_v, beta, N, facility_idx, hosp_begin, max_d))
}

#'@param alpha facility effect for each person, length-N vector
#'@param alpha_star facility effect for each facility, length-num_facility vector
#'@param num_events total number of events
#'@param O number of events by facility
update_beta <- function(l, lchange, L1, L2, Sm, t_start, t_end, events_per_day_facility, z, Z_tv, t_tv, max_v, beta, update, facility_idx, hosp_begin, max_d) {
    invisible(.Call('_tdrecur_update_beta', PACKAGE = 'tdrecur', l, lchange, L1, L2, Sm, t_start, t_end, events_per_day_facility, z, Z_tv, t_tv, max_v, beta, update, facility_idx, hosp_begin, max_d))
}

#'Estimate beta, lambda, and alpha
#'
#'@param max_d the largest number of hospitalization in each segment
#'@param delta indicator vector of event
#'@param z design matrix
#'@param tol tolerance of precision, when highest change in beta is lower than or equal to tol, iteration stops
#'@param facility 1 to num_facility
#'
#'@return estimated beta, lambda, alpha
#'
#'
#'@export
cox_breslow_dep <- function(hosp_begin, max_d, t_start, t_end, z, Z_tv, t_tv, max_v, tolb, tola, maxiter, facility, num_facility, D, beta) {
    .Call('_tdrecur_cox_breslow_dep', PACKAGE = 'tdrecur', hosp_begin, max_d, t_start, t_end, z, Z_tv, t_tv, max_v, tolb, tola, maxiter, facility, num_facility, D, beta)
}

#' created on 12/11/2021: this one use stratified model
NULL

compute_facility_idx <- function(facility, num_facility) {
    .Call('_tdrecur_compute_facility_idx', PACKAGE = 'tdrecur', facility, num_facility)
}

#' this function calculates Sm (1 by p), sum of z in event set; O, the vector of total events in each
#' facility; num_events, number of all events; events_per_day_facility, number of events each day in each facility
#'@param hosp_begin matrix of hospitalization begin date
#'@param max_d the largest number of hospitalization in each segment
#'@param D number of distinct failure time number of days)
#'@param z time-independent variables
compute_d12 <- function(hosp_begin, max_d, D, z, facility, num_facility) {
    .Call('_tdrecur_compute_d12', PACKAGE = 'tdrecur', hosp_begin, max_d, D, z, facility, num_facility)
}

#'@param l log partial likelihood
#'@param S0 D+1 vector, we will do day 0 (begining of day 1) to day D (end of day D)
#'@param t_start a vector of segment start date, starting from 1, minus 1 when using it.
#'@param t_end a vector of segment end date, starting from 1.
#'@param Sm p by 1 vector
#'@param ym number of changes on each day
#'@param exp_z_beta vector of exp(zi * beta + alphai), length N, with repeated KECC_ID
ddloglik_cpp6 <- function(L1, L2, S0, t_start, t_end, Sm, events_per_day_facility, exp_z_beta, z, beta, facility_idx) {
    invisible(.Call('_tdrecur_ddloglik_cpp6', PACKAGE = 'tdrecur', L1, L2, S0, t_start, t_end, Sm, events_per_day_facility, exp_z_beta, z, beta, facility_idx))
}

#'@param alpha facility effect for each person, length-N vector
#'@param alpha_star facility effect for each facility, length-num_facility vector
#'@param num_events total number of events
#'@param O number of events by facility
update_beta <- function(L1, L2, S0, Sm, t_start, t_end, events_per_day_facility, exp_z_beta0, z, beta, update, z_beta, facility, num_facility, D, N, facility_idx) {
    invisible(.Call('_tdrecur_update_beta', PACKAGE = 'tdrecur', L1, L2, S0, Sm, t_start, t_end, events_per_day_facility, exp_z_beta0, z, beta, update, z_beta, facility, num_facility, D, N, facility_idx))
}

#'@param l log partial likelihood
#'@param S0 D+1 vector, we will do day 0 (begining of day 1) to day D (end of day D)
#'@param t_start a vector of segment start date, starting from 1, minus 1 when using it.
#'@param t_end a vector of segment end date, starting from 1.
#'@param Sm p by 1 vector
#'@param ym number of changes on each day
#'@param exp_z_beta vector of exp(zi * beta + alphai), length N, with repeated KECC_ID
ddloglik_Ui <- function(L1, L2, S0, t_start, t_end, Sm, events_per_day_facility, exp_z_beta, z, beta, facility_idx, hosp_begin, max_d) {
    .Call('_tdrecur_ddloglik_Ui', PACKAGE = 'tdrecur', L1, L2, S0, t_start, t_end, Sm, events_per_day_facility, exp_z_beta, z, beta, facility_idx, hosp_begin, max_d)
}

#'@param l log partial likelihood
#'@param S0 D+1 vector, we will do day 0 (begining of day 1) to day D (end of day D)
#'@param t_start a vector of segment start date, starting from 1, minus 1 when using it.
#'@param t_end a vector of segment end date, starting from 1.
#'@param Sm p by 1 vector
#'@param ym number of changes on each day
#'@param exp_z_beta vector of exp(zi * beta + alphai), length N, with repeated KECC_ID
ddloglik_cpp11 <- function(S0, t_start, t_end, exp_z_beta) {
    invisible(.Call('_tdrecur_ddloglik_cpp11', PACKAGE = 'tdrecur', S0, t_start, t_end, exp_z_beta))
}

#'@param alpha facility effect for each person, length-N vector
#'@param alpha_star facility effect for each facility, length-num_facility vector
#'@param num_events total number of events
#'@param O number of events by facility
update_alpha11 <- function(alpha, S0, t_start, t_end, dm, exp_z_beta, exp_z_beta0, diffalpha, alpha_star, facility, num_facility, D, lambda, num_events, O, N, Epre) {
    invisible(.Call('_tdrecur_update_alpha11', PACKAGE = 'tdrecur', alpha, S0, t_start, t_end, dm, exp_z_beta, exp_z_beta0, diffalpha, alpha_star, facility, num_facility, D, lambda, num_events, O, N, Epre))
}

#'Estimate beta, lambda, and alpha
#'
#'@param hosp_begin matrix of event time for each participant
#'@param max_d number of events for each row (participant)
#'@param delta indicator vector of event
#'@param z design matrix
#'@param tol tolerance of precision, when highest change in beta is lower than or equal to tol, iteration stops
#'@param facility 1 to num_facility
#'@param beta initial value for beta
#'
#'@return estimated beta, lambda, alpha
#'
#'
#'@export
cox_breslow_ind <- function(hosp_begin, max_d, t_start, t_end, z, tolb, tola, maxiter, facility, num_facility, D, beta) {
    .Call('_tdrecur_cox_breslow_ind', PACKAGE = 'tdrecur', hosp_begin, max_d, t_start, t_end, z, tolb, tola, maxiter, facility, num_facility, D, beta)
}

